version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - '8081:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - 'db:psql-server'

volumes:
  db-data:
  pgadmin-data:
