version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: dev-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: S3cret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.7
    container_name: dev-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: S3cret
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:postgres-server

volumes:
  db-data:
  pgadmin-data:
